![alt text](http://infra.heurys.com.br/summerschool/exercicio.02.png)

**1.   Criar uma função que receba duas matrizes 3 x 3 e multiplique um elemento pelo outro.**

$\begin{bmatrix}
  1 & 2 & 3 \\
  4 & 5 & 6 \\
  7 & 8 & 9 \\
\end{bmatrix} *
\begin{bmatrix}
  2 & 3 & 4 \\
  2 & 3 & 4 \\
  2 & 3 & 4 \\
\end{bmatrix} =
\begin{bmatrix}
  2 & 6 & 12 \\
  8 & 15 & 24 \\
  14 & 24 & 36 \\
\end{bmatrix}$

In [1]:
# Resposta do exercício 1
import numpy as np

matriz_a = np.array([[1,2,3],[4,5,6],[7,8,9]])
matriz_b = np.array([[2,3,4],[2,3,4],[2,3,4]])

multiplica_matriz = lambda a,b : a * b

resultado = multiplica_matriz(matriz_a, matriz_b)

print('Resultado:\n', resultado)

Resultado:
 [[ 2  6 12]
 [ 8 15 24]
 [14 24 36]]


**2.   Criar uma função que multiplique um array 1 x 4 pelo valor 5.**

$\begin{bmatrix}
  1 & 2 & 3 & 4 \\
\end{bmatrix} *
5 =
\begin{bmatrix}
  5 & 10 & 15 & 20 \\  
\end{bmatrix}$


In [2]:
# Resposta do exercício 2
import numpy as np

array = np.array([1,2,3,4])

def multiplica(a):
  return a * 5

resultado = multiplica(array)

print('Resultado:\n', resultado)

Resultado:
 [ 5 10 15 20]


**3.   Criar uma rotina que receba uma martiz 5 x 5 e troque a primeira linha pela segunda **

$\begin{bmatrix}
  1 & 2 & 3 & 4 & 5 \\
  6 & 7 & 8 & 9 & 10\\
  11 & 12 & 13 & 14 & 15\\
  16 & 17 & 18 & 19 & 20\\
  21 & 22 & 23 & 24 & 25\\
\end{bmatrix} < = >
\begin{bmatrix}
  6 & 7 & 8 & 9 & 10\\
  1 & 2 & 3 & 4 & 5 \\
  11 & 12 & 13 & 14 & 15\\
  16 & 17 & 18 & 19 & 20\\
  21 & 22 & 23 & 24 & 25\\
\end{bmatrix}
$

In [3]:
# Resposta do exercício 3

import numpy as np

matriz = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])

print('Matriz original:\n', matriz, '\n')

matriz[[0,1]] = matriz[[1,0]]

print('Matriz final:\n', matriz)

Matriz original:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]] 

Matriz final:
 [[ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


**4.   Dada a tabela abaixo de vendas, vamos prever os 3 meses faltantes através de regressão linear. (utilizar apenas numpy e matlibplot) **



<table style='border: 1px solid black;'>
  <tr><th width='50px' align="left">Mês</th><th width='100px' align="right">Qtde. Cliente</th><th width='150px' align="right">Total de Vendas(K)</th></tr>
   <tr><td>Jan</td><td align="right">730</td><td align="right">9.85</td></tr>
   <tr><td>Fev</td><td align="right">880</td><td align="right">10.20</td></tr>
   <tr><td>Mar</td><td align="right">505</td><td align="right">6.44</td></tr>
   <tr><td>Abr</td><td align="right">529</td><td align="right">7.07</td></tr>
   <tr><td>Mai</td><td align="right">872</td><td align="right">9.91</td></tr>
   <tr><td>Jun</td><td align="right">907</td><td align="right">11.20</td></tr>
   <tr><td>Jul</td><td align="right">926</td><td align="right">11.03</td></tr>
   <tr><td>Ago</td><td align="right">679</td><td align="right">7.24</td></tr>
   <tr><td>Set</td><td align="right">452</td><td align="right">9.43</td></tr>  
</table>

<br>

O objetivo desse cálculo é prever os valores de uma variável dependente (Y) com base em resultados da variável independente (X).

Gostaríamos de prever os totais de vendas para os meses de Out, Nov e Dez, caso meus clientes sejam 500, 750, 1000 respectivamente.


A fórmula da regressão linear é:

$
\begin{equation*}
Y = a + bX
\end{equation*}
$

onde,

$X$ = Qtde. de Clientes que vamos prever

$Y$ = Total de Vendas previsto

$a$ e $b$ = São os dois coeficientes de regressão, necessários para fazermos a reta de regressão. 

\\

**Fórmulas:**

\\
Para calcular **a**:


$
\begin{equation*}
a = \overline{y} -b \, \overline{x}
\end{equation*}
$

Para calcular **b**:


$
\begin{align}
b = \frac{ \sum xy  -n \: \overline{xy}}{\sum x^2 - n \: \overline{x}^2 }
\end{align}
$


onde:

$x$ = Qtde. de Clientes dos meses conhecidos

$y$ = Total de Vendas dos meses conhecidos

$n$ = Qtde. de meses

$
\begin{align}
\overline{x} \end{align} $ = média de $x$

$
\begin{align}
\overline{y} \end{align} $ = média de $y$



In [3]:
# Resposta do exercício 4
import numpy as np

# qtde de clientes (x)
x = np.array([730, 880, 505, 529, 872, 907, 926, 679, 452]).reshape(-1,1)

# total de vendas (y)
y = np.array([9.85, 10.20, 6.44, 7.07, 9.91, 11.20, 11.03, 7.24, 9.43]).reshape(-1,1)

             
# clientes previstos para os meses de Out, Nov e Dez
X_estimado = np.array([500, 750, 1000]).reshape(-1,1)


# vamos definir todas as variáveis que precisamos para calcular
n = x.size

x_2 = x ** 2

xy = x * y

x_avg = np.average(x)
y_avg = np.average(y)

x_2_sum = np.sum(x_2)
xy_sum = np.sum(xy)

# vamos calcular b
b = (xy_sum - n * x_avg * y_avg) / (x_2_sum - n * x_avg ** 2)

# vamos calcular a
a = y_avg - b * x_avg


# vamos prever os dados
Y_previsto = np.array(list(map(lambda item : a + b * item, X_estimado)))


print('Intercept', a)
print('Coefficient', b, '\n')

print('Clientes estimados: ', X_estimado.ravel())
print('Venda prevista: ', Y_previsto.ravel())


# Para exibir o gráfico
import matplotlib.pyplot as plt


# vamos mostrar os pontos atuais de nossa tabela
plt.scatter(x, y, color='blue')

# vamos mostrar os pontos previstos
plt.scatter(X_estimado, Y_previsto, color='green')

# vamos mostrar a reta
plt.plot(X_estimado, Y_previsto, color='red')


plt.title('Regressão Linear', fontsize=16)
plt.xlabel('Clientes', fontsize=13)
plt.ylabel('Total de Vendas', fontsize=13)

plt.show()


x2: [[532900]
 [774400]
 [255025]
 [279841]
 [760384]
 [822649]
 [857476]
 [461041]
 [204304]]
x_2_sum: [[532900]
 [774400]
 [255025]
 [279841]
 [760384]
 [822649]
 [857476]
 [461041]
 [204304]]
282420.0


"\n\n\nb = (xy_sum - n * x_avg * y_avg) / (x_2_sum - n * x_avg ** 2)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n# vamos calcular b\n\n# vamos calcular a\na = y_avg - b * x_avg\n\n\n# vamos prever os dados\nY_previsto = np.array(list(map(lambda item : a + b * item, X_estimado)))\n\n\nprint('Intercept', a)\nprint('Coefficient', b, '\n')\n\nprint('Clientes estimados: ', X_estimado.ravel())\nprint('Venda prevista: ', Y_previsto.ravel())\n\n\n# Para exibir o gráfico\nimport matplotlib.pyplot as plt\n\n\n# vamos mostrar os pontos atuais de nossa tabela\nplt.scatter(x, y, color='blue')\n\n# vamos mostrar os pontos previstos\nplt.scatter(X_estimado, Y_previsto, color='green')\n\n# vamos mostrar a reta\nplt.plot(X_estimado, Y_previsto, color='red')\n\n\nplt.title('Regressão Linear', fontsize=16)\nplt.xlabel('Clientes', fontsize=13)\nplt.ylabel('Total de Vendas', fontsize=13)\n\nplt.show()\n"